### PR TITLE
Add autoload cookies for public functions

### PR DESCRIPTION
**Pull request by rlaboiss**
Autoload cookies are added for functions org-recoll-update-index and
org-recoll-search.  This is very handy when installing the package through
el-get.

### CODE REVIEW

**Comment by alraban** [comment]
Will the addition of these cookies have any effect on emacs instances that don't currently invoke autoload?  It seems that they won't, but I ask because the autoload documentation appears a little unclear on that point.  I don't currently use autoload, so I'm learning as I go.

**Comment by rlaboiss** [comment]
Those cookies are just comments in the source file, so they should have no side effects.  I wrote a recipe for intalling org-recoll via el-get and the set up is much simpler if the cookies are present,  Otherwise, the two autoloads must be done manually.  I do not know if this also helps in installing the org-recoll via package.el, but that might also be the case.

**Comment by alraban** [comment]
Sounds good to me, I'll pull it now.

**Comment by rlaboiss** [comment]
> Sounds good to me, I'll pull it now.

Thanks! I will soon propose a recipe in [el-get](https://github.com/dimitri/el-get) and let you know when it is done. The autoload cookies will be very handy for that.

**Comment by rlaboiss** [comment]
It is done: [PR#2688](https://github.com/dimitri/el-get/pull/2688)

**Pull request merged**
